listaDeProductos = [
    {
        id: 1,
        titulo: "Bicicleta Montaña Merida Big Nine 8000",
        imagen: "./imagenes/biciletas/merida/big8000.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "Merida",
        precio: 2988690,
        description: ["La Bicicleta Merida Big Nine 8000 es adecuada para conducción general, viajes por la ciudad y viajes de larga distancia.",
            "Es rápida, confiable, liviana y versátil. Los ingenieros de Mérida nos prepararon una sorpresa: un Big Nine aún más cómodo y pasable, cuya característica distintiva son las ruedas Maxxis Ikon de 29 pulgadas. El Big Nine 8000 está construido sobre un cuadro de carbono. Transmisión Sram Carbon GX Eagle: 34 una rueda dentada adelante, 10-52 cassette atrás.",
        ],
        talle: "S",
        cantidad: 2,
    }, {
        id: 2,
        titulo: "Bicicleta Montaña Merida Big Nine 8000",
        imagen: "./imagenes/biciletas/merida/big9000.png",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "merida",
        precio: 3018690,
        description: ["La Bicicleta Merida Big Nine 9000 es adecuada para conducción general, viajes por la ciudad y viajes de larga distancia.",
            "Es rápida, confiable, liviana y versátil. Los ingenieros de Mérida nos prepararon una sorpresa: un Big Nine aún más cómodo y pasable, cuya característica distintiva son las ruedas Maxxis Ikon de 29 pulgadas. El Big Nine 8000 está construido sobre un cuadro de carbono. Transmisión Sram Carbon GX Eagle: 34 una rueda dentada adelante, 10-52 cassette atrás.",
        ],
        talle: "L",
        cantidad: 1,
    }, {
        id: 3,
        titulo: "Bicicleta de Montaña Cube Elite C:68X Race Carbon 29",
        imagen: "./imagenes/biciletas/cube/cubec68xrace.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "merida",
        precio: 2985490,
        description: ["La eficiencia, ligereza y comodidad del cuadro de la Elite C:68X Race juegan un papel fundamental en esta tarea.",
            "La eficiencia, ligereza y comodidad del cuadro de la Elite C:68X Race juegan un papel fundamental en esta tarea. Como también lo hacen sus ruedas Newmen Evolution, compatibles con sistema tubeless sin cámara, sus neumáticos Schwalbe ligeros y plegables y su nueva horquilla RockShox SID SL Ultimate. Al combinar todo esto con unos potentes frenos de disco hidráulicos Shimano XT y con la precisión de cambio de una transmisión Sram XX1 1x12 de amplio rango, se consigue un ritmo implacable unido a un control y una comodidad increíbles.",
        ],
        talle: "L",
        cantidad: 1,
    }, {
        id: 4,
        titulo: "Bicicleta Montaña Merida Ninety SIX RC XT",
        imagen: "./imagenes/biciletas/merida/ninetysix.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "merida",
        precio: 2432530,
        description: ["La bicicleta de montaña Merida Ninety Six RC XT regresa mejor que nunca en 2021, lista para satisfacer las necesidades del corredor de XC moderno que quiere rodar en su mejor momento.",
            "La bicicleta de montaña Merida Ninety Six RC XT regresa mejor que nunca en 2021, lista para satisfacer las necesidades del corredor de XC moderno que quiere rodar en su mejor momento. Mérida ha realizado grandes cambios en este modelo este año con un cuadro de carbono CF4 III completamente nuevo que es más elegante que el modelo anterior, construido para la combinación definitiva de durabilidad y velocidad. La geometría actualizada está diseñada teniendo en cuenta las preferencias de conducción modernas, construida con un ángulo de cabeza más flojo y un ángulo de asiento más pronunciado para combinar con una distancia entre ejes y un alcance más largos.",
        ],
        talle: "M",
        cantidad: 1,
        id: 5,
        titulo: "Bicicleta de Montaña Cube Elite C:68X Pro 29",
        imagen: "./imagenes/biciletas/cube/cubec68xpro.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 2389070,
        description: ["La nueva Elite C:68X Pro aprovecha la comodidad y velocidad increíbles de nuestra plataforma cross-country de carbono de alta calidad C:68X y las combina con una cuidada selección de componentes fiables.",
            "La nueva Elite C:68X Pro aprovecha la comodidad y velocidad increíbles de nuestra plataforma cross-country de carbono de alta calidad C:68X y las combina con una cuidada selección de componentes fiables. La transmisión Shimano 1x12 XT no necesita presentación, y las bielas Praxis Girder de carbono reducen el peso sin sacrificar el rendimiento. Los potentes frenos de disco hidráulicos Shimano XT son lo último en seguridad de frenada, y la horquilla Fox 32 Step-Cast se une a unas ruedas ligeras compatibles con cubiertas tubeless y a unos neumáticos Schwalbe con talón de kevlar que te llevarán directo a la línea de meta.",
        ],
        talle: "M",
        cantidad: 1,
    }, {
        id: 6,
        titulo: "Bicicleta de MTB Cube Reaction C62 SL",
        imagen: "./imagenes/biciletas/cube/cubec62sl.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 1639520,
        description: ["Has acumulado kilómetros y ahora es el momento de ponerte a prueba en la competición. Si eres esta persona, entonces llevas tiempo esperando por la Reaction C:62 SL.",
            "Has acumulado kilómetros y ahora es el momento de ponerte a prueba en la competición. Si eres esta persona, entonces llevas tiempo esperando por la Reaction C:62 SL. Equipada con la nueva horquilla RockShox SID Select y un juego de ruedas ligero y rígido preparado para montaje sin cámaras Fulcrum Red 77 y calzado con neumáticos Schwalbe de gran agarre con dibujo Kevlar, es el cohete ligero que estabas esperando. Las marchas Sram 1x12 de gran precisión ofrecen un rango amplio para los recorridos más abruptos y los potentes frenos de disco hidráulicos de Magura te proporcionan la energía que necesitas para darlo todo en la competición. Parece rápida porque es rápida.",
        ],
        talle: "S",
        cantidad: 1,
    }, {
        id: 7,
        titulo: "Bicicleta de carbono MTB Cube Reaction C62 Race",
        imagen: "./imagenes/biciletas/cube/cubec62race.png",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 1560030,
        description: ["La Reaction C:62 Race desprende carácter competitivo por cada uno de los tubos y componentes de su cuadro, de ahí que se haya ganado el sobrenombre de «Race». Y sí, es justamente tan rápida como parece.",
            "La Reaction C:62 Race desprende carácter competitivo por cada uno de los tubos y componentes de su cuadro, de ahí que se haya ganado el sobrenombre de «Race». Y sí, es justamente tan rápida como parece. Su elegante chasis condensa todo lo que nuestro equipo de ingenieros ha aprendido sobre la fabricación de cuadros de carbono de alto rendimiento en un cuadro ligero, resistente y receptivo. Desde sus cortas vainas y eje trasero Boost hasta sus delgados tirantes capaces de absorber cualquier vibración o su tubo de dirección cónico, cada detalle ha sido perfeccionado para la velocidad y la eficiencia. Lo cual significa, por descontado, que no hemos escatimado en componentes: contiene todo lo que un corredor ambicioso podría llegar a necesitar en una temporada con aspiraciones de podio. Una horquilla RockShox Reba con bloqueo remoto, la legendaria transmisión Sram 1x12 y frenos de disco hidráulicos Shimano XT, un juego de ruedas Answer Attack calzadas con cubiertas Schwalbe y componentes Newmen en el puesto de mando: no hay duda de que esta bicicleta te permitirá rendir al máximo. ¿Estás listo para poner a prueba tus límites? Porque, sin ninguna duda, la Reaction C:62 lo está.",
        ],
        talle: "XL",
        cantidad: 1,
    }, {
        id: 8,
        titulo: "Bicicleta de Montaña Carbono Cube Reaction C:62 Race 29",
        imagen: "./imagenes/biciletas/cube/cubec62race.png",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 1638030,
        description: ["Cada milímetro de su elegante cuadro y sus soberbios componentes desprende su carácter competitivo, porque la Reaction C:62 Race es tu pase VIP al podio.",
            " Con un juego de ruedas Answer Attack AM preparado para montaje sin cámaras y los neumáticos plegables Kevlar, acelera rapidísimo gracias a los rapidísimos cambios de marchas de la transmisión Shimano 1x12. Para ayudar a mantener la rueda agarrada al suelo y la dirección donde procede, cuenta con la horquilla de suspensión Fox Performance 32 Step-Cast y los frenos de disco hidráulicos Shimano XT te proporcionan toda la potencia que necesitas para mantener el control en subidas y descensos.",
        ],
        talle: "M",
        cantidad: 1,
    }, {
        id: 9,
        titulo: "Bicicleta de Montaña Carbono Cube Reaction C:62 Pro 29",
        imagen: "./imagenes/biciletas/cube/cubec62pro.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 1363480,
        description: ["El bajo peso, la conducción precisa de Reaction C:62 Pro y la sorprendente comodidad durante el trayecto te proporcionan esa dosis de fuerza que necesitas para seguir adelante.",
            "Esta fabricada con componentes seleccionados altamente fiables de 12 marchas de Shimano por sus suaves cambios y el amplio rango de marchas que ofrecen, y hemos añadido los potentes frenos de disco hidráulicos de Shimano XT (con un rotor más grande en la parte delantera) para asegurarnos de que siempre tengas el control total. Además, con su fácil ajuste y su suave rendimiento, la horquilla de suspensión de aire RockShox Judy Gold ayuda a mantener la rueda delantera en su sitio y apuntando en la dirección adecuada.",
        ],
        talle: "M",
        cantidad: 1,
    }, {
        id: 10,
        titulo: "Bicicleta de Gravel Carbono Cube Nuroad C:62 PRO 28",
        imagen: "./imagenes/biciletas/cube/gravel1.jpg",
        categoria: {
            id: "ruta",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 924805,
        description: "Llegó la nueva línea de Bicicletas de Gravel de la marca Cube, ahora en este formato de carbono y equipada con los mejores componentes",
        talle: "56",
        cantidad: 1,
    }, {
        id: 11,
        titulo: "Bicicleta de Ruta rod 28 Cube Attain GTC Race Carbon 28",
        imagen: "./imagenes/biciletas/cube/rutagtc1.jpg",
        categoria: {
            id: "ruta",
            nombre: "bicicleta",
            nmaterial: "carbono",
        },
        marca: "cube",
        precio: 1068050,
        description: ["La Bicicleta Merida Big Nine 8000 es adecuada para conducción general, viajes por la ciudad y viajes de larga distancia.",
            " Equipada con las legendarias y confiables marchas Shimano 105 2x11 y frenos de disco hidráulicos a juego, y también se pueden instalar guardabarros. Los neumáticos Continental Grand Sport Race SL en un juego de ruedas CUBE Aero Disc con llantas más anchas garantizan agarre y control en todo tipo de clima, y ​​los componentes de acabado CUBE y un sillín Natural Fit completan el paquete.",
        ],
        talle: "53",
        cantidad: 1,
    }, {
        id: 12,
        titulo: "Bicicleta de Montaña Cube Reaction C:62 One Carbon 29",
        imagen: "./imagenes/biciletas/cube/cubec622021.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 1071590,
        description: ["Nunca antes había sido tan buen momento para disfrutar del rendimiento de un cuadro de carbono. La nueva Reaction C:62 One combina peso reducido, una comodidad sublime y una conducción de carbono definida con la transmisión precisa 1x12 de Sram."],
        talle: "M",
        cantidad: 1,
    }, {
        id: 13,
        titulo: "Bicicleta de MTB Carbono Cube Reaction C:62 One 29 (Nuevo)",
        imagen: "./imagenes/biciletas/cube/cubec62nuevo22.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "carbono",
        },
        marca: "cube",
        precio: 1193380,
        description: "Nunca antes había sido tan buen momento para disfrutar del rendimiento de un cuadro de carbono. La nueva Reaction C:62 One combina peso reducido, una comodidad sublime y una conducción de carbono definida.",
        talle: "XL",
        cantidad: 1,
    }, {
        id: 14,
        titulo: "Bicicleta de Ruta Cube Nuroad Pro 28",
        imagen: "./imagenes/biciletas/cube/cubepro282021.jpg",
        categoria: {
            id: "ruta",
            nombre: "bicicleta",
            material: "aluminio",
        },
        marca: "cube",
        precio: 709943,
        description: "La versatilidad de ir a cualquier parte tiene un nuevo nombre: la nueva Nuroad Pro ofrece la mayor holgura para los neumáticos que se han ofrecido..",
        talle: "S",
        cantidad: 2,
    }, {
        id: 15,
        titulo: "Bicicleta de MTB Aluminio Cube Acid 29 (Nuevo)",
        imagen: "./imagenes/biciletas/cube/cubeacid2022.jpg",
        categoria: {
            id: "mtb",
            noombre: "bicicleta",
            material: "aluminio",
        },
        marca: "cube",
        precio: 728328,
        description: "Totalmente renovada para el 2022, la estetica elegante de la nueva Acid es fruto de las soldaduras lisas de las juntas del tubo de direccion y del cano de asiento. Incluye un eje de pedalier de rosca y los cables estan colocados internamente.",
        talle: "L",
        cantidad: 1,
    }, {
        id: 16,
        titulo: "Bicicleta de MTB Aluminio Cube Attention SL 29",
        imagen: "./imagenes/biciletas/cube/cubeatention.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicileta",
            material: "aluminio",
        },
        marca: "cube",
        precio: 693493,
        description: "Hay dos razones para adorar la Attention SL. En primer lugar, la horquilla de aire RockShox Judy Silver combina un ajuste fácil con un rendimiento suave y fiable en cualquier terreno pedregoso y una dirección precisa.",
        talle: "L",
        cantidad: 1,
    }, {
        id: 17,
        titulo: "Bicicleta de Ruta Aluminio Cube Attain Pro 28",
        imagen: "./imagenes/biciletas/cube/cuberuta2.jpg",
        categoria: {
            id: "ruta",
            nombre: "bicicleta",
            material: "aluminio",
        },
        marca: "cube",
        precio: 613610,
        description: "No hay nada que supere a los frenos de disco en su potencia de frenada segura y determinante en todo tipo de condiciones meteorológicas. Por eso hemos equipado la Attain Pro con frenos fiables y por cable de TRP.",
        talle: "50",
        cantidad: 1,
    }, {
        id: 18,
        titulo: "Bicicleta de Montaña Cube Attention SL",
        imagen: "./imagenes/biciletas/cube/cubeatention2021.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "aluminio",
        },
        marca: "cube",
        precio: 574360,
        description: "Hay dos razones para adorar la Attention SL. En primer lugar, la horquilla de aire RockShox Judy Silver combina un ajuste fácil con un rendimiento suave y fiable en cualquier terreno pedregoso y una dirección precisa.",
        talle: "L",
        cantidad: 1,
    }, {
        id: 19,
        titulo: "Bicicleta de Montaña Cube Acid 29",
        imagen: "./imagenes/biciletas/cube/cubeacid2021.jpg",
        categoria: {
            id: "mtb",
            nombre: "bicicleta",
            material: "aluminio",
        },
        marca: "cube",
        precio: 579936,
        description: "Es el momento de replantearse cómo de buena debe ser una rígida de trail. La transmisión Sram NX Eagle 1x12 de Acid está concebida para ofrecer unos cambios precisos y rápidos vez tras vez, con un rango de marchas lo suficientemente amplio.",
        talle: "M",
        cantidad: 1,
    }, {
        id: 20,
        titulo: "Bicicleta de Ruta Aluminio Cube Attain 28",
        imagen: "./imagenes/biciletas/cube/cuberuta3.jpg",
        categoria: {
            id: "ruta",
            nombre: "bicicleta",
            material: "aluminio",
        },
        marca: "cube",
        precio: 491504,
        description: "Nueva versión de la bicicleta rutera de la marca Cube, modelo Attain 2022.",
        talle: "50",
        cantidad: 2,
    },/*{
            id: 21,
            titulo: "",
            imagen: "./imagenes/grupos/sram/electronico1.jpg",
            categoria: {
                id: "horquilla",
            },
            precio: "$1.440.360",
            description: "El set de grupo de cambios de 6 agujeros de SRAM Red eTap AXS™ HRD FM para 2x12 disco te ofrece un equipo con funciones intuitivas orientadas al rendimiento.",
        }, {
            id: 22,
            titulo: "",
            imagen: "./imagenes/grupos/sram/electronico2.jpg",
            categoria: {
                id: "horquilla",
            },
            precio: "$888.618",
            description: "Grupo de bicicleta de ruta Electrónico Inalambrico 2x12 Sram Force AXS, con frenos de disco hidraulicos, para núcleos XDR.",
          
        }, {
            id: 23,
            titulo: "",
            imagen: "./imagenes/grupos/sram/gxEgle.jpg",
            categoria: {
                id: "horquilla",
            },
            precio: "$264.968",
            description: "GX Eagle combina la capacidad completa de las tecnologías Eagle, en un grupo que se da cuenta del potencial dentro de cada construcción. Aquí es donde encontrarás las mejores bielas de aluminio para MTB.",
            
        },*/{
        id: 24,
        titulo: "Plato Palanca MTB Sram XX1 Eagle, DUB 12v",
        imagen: "./imagenes/grupos/sram/sram-imagen1.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 264968,
        cantidad: 10,
        description: "Juego de plato palanca Sram XX1 Eagle de 12 velocidades para bicicleta de montaña, bielas de 170mm, eje DUB y plato de 34 dientes.",
    }, {
        id: 25,
        titulo: "Palancas MTB Sram 12v XX1 Eagle DUB Grey",
        imagen: "./imagenes/grupos/sram/sram-imagen2.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 264968,
        cantidad: 10,
         description: "Juego de plato palanca Sram XX1 Eagle de 11/12 velocidades para bicicleta de montaña, bielas de 170mm, eje DUB y plato de 34 dientes.",
    }, {
        id: 26,
        titulo: "Plato Palanca MTB Sram X01 Eagle Carbon DUB 12v",
        imagen: "./imagenes/grupos/sram/sram-imagen3.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 206021,
        cantidad: 10,
        description: "Juego de plato palanca Sram X01 Eagle de 12 velocidades para bicicleta de montaña, bielas de 170mm, eje DUB y plato de 32 dientes.",
    }, {
        id: 27,
        titulo: "Piñon MTB Sram X01 Eagle XG-1295 12v 10-50d XD Polar Grey",
        imagen: "./imagenes/grupos/sram/sram-imagen4.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 191284,
        description: "Piñon de Bicicleta de montaña del grupo Sram X01 Eagle de 12 velocidades, con dentado 10-50 y compatible con núcleos XD.",
    }, {
        id: 28,
        titulo: "Cambio Trasero SRAM MTB 12v 52d XX1 Eagle Lunar",
        imagen: "./imagenes/grupos/sram/sram-imagen5.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 161810,
        cantidad: 10,
        description: "La sensación de cambio nítida y precisa de XX1 ™ en la que confían los atletas ahora presenta una geometría de jaula actualizada para una mejor gestión de la cadena.",
    }, {
        id: 29,
        titulo: "Piñon SRAM 12v MTB XG-1295 10-50d XD Black (X01 Eagle)",
        imagen: "./imagenes/grupos/sram/sram-imagen6.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 191284,
        cantidad: 10,
        description: "Piñon de Bicicleta de montaña del grupo Sram X01 Eagle de 12 velocidades, con dentado 10-50. Compatible con núcleo XD.",
    }, {
        id: 30,
        titulo: "Plato Palanca MTB Sram GX Carbon Eagle, DUB 12v, 170mm 32T Boost 148 DM Lunar",
        imagen: "./imagenes/grupos/sram/sram-imagen7.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 155916,
        cantidad: 10,
       description: "Plato-Palanca para bicicletas de montaña Sram Carbon GX Eagle, con Monoplato de 32 dientes, para sistemas de 12 velocidades. El largo de las bielas es de 170mm y el eje es DUB.",
    }, {
        id: 31,
        titulo: "Shifter Gripshift MTB Sram XX1 Eagle 1x12v",
        imagen: "./imagenes/grupos/sram/sram-imagen8.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 79284,
        cantidad: 10,
        description: "Gripshift de bicicleta de Montaña Sram XX1 Eagle , de 12 velocidades.",
    }, {
        id: 32,
        titulo: "Shifter Trasero MTB Sram XX1 Eagle Trigger 12v Lunar",
        imagen: "./imagenes/grupos/sram/sram-imagen9.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 88126,
        cantidad: 10,
        description: "Shifter Trasero para bicicletas de MTB Sram XX1 Eagle Trigger 12v.",
    }, {
        id: 33,
        titulo: "Cambio Trasero Sram GX Eagle 12v 52d Long Cage Lunar",
        imagen: "./imagenes/grupos/sram/sram-imagen10.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 64253,
        cantidad: 10,
       description: "Descarrilador trasero - 12 velocidades - Para platos con un maximo de 52 dientes - Jaula larga de Aluminio.",
    }, {
        id: 34,
        titulo: "Plato Palanca MTB Sram SX Eagle DUB 12v, 175mm 32T DM",
        imagen: "./imagenes/grupos/sram/sram-imagen11.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 52758,
        cantidad: 10,
        description: "Juego de plato palanca Sram SX Eagle de 12 velocidades para bicicleta de montaña, bielas de 175mm, eje DUB y plato de 32 dientes.",
    }, {
        id: 35,
        titulo: "Shifter Gripshift MTB Sram X01 Eagle 1x12v",
        imagen: "./imagenes/grupos/sram/sram-imagen12.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 60999,
        cantidad: 10,
        description: "Gripshift de bicicleta de Montaña Sram X01 Eagle de 12 velocidades.",
    }, {
        id: 36,
        titulo: "Cambio Trasero SRAM MTB 12v 50d NX Eagle",
        imagen: "./imagenes/grupos/sram/sram-imagen13.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 52758,
        cantidad: 10,
        description: "Cambio trasero de bicicleta de montaña Sram NX Eagle de 12 velocidades..",
    }, {
        id: 37,
        titulo: "Cambio Trasero de Bicicleta de Montaña Sram SX Eagle 12 velocidades.",
        imagen: "./imagenes/grupos/sram/sram-imagen14.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 46863,
        cantidad: 10,
        description: "Cambio trasero de 12 velocidades para bicicletas de montaña Sram SX Eagle.",
    }, {
        id: 38,
        titulo: "Cambio Trasero Sram Force 22 11v Short Cage 28T Silver",
        imagen: "./imagenes/grupos/sram/sram-imagen15.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 49810,
        cantidad: 10,
       description: "Adoptando todas las tecnologías que proporcionan cambios rápidos y silenciosos, el cambio trasero SRAM Force 22 ha sido diseñado con la tecnología EXACT ACTUATION ™ para cambios precisos y eficientes en toda la gama de cambios.",
    }, {
        id: 39,
        titulo: "Cambio Trasero SRAM MTB 12v 50d SX Eagle Long Cage",
        imagen: "./imagenes/grupos/sram/sram-imagen16.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 46863,
        cantidad: 10,
        description: "Cambio trasero de 12 velocidades para bicicletas de montaña Sram SX Eagle.",
    }, {
        id: 40,
        titulo: "Cambio Trasero Sram Apex 1 11v 42T Long Cage",
        imagen: "./imagenes/grupos/sram/sram-imagen17.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 40968,
        cantidad: 10,
        description: "Descarrilador trasero - 11 velocidades - Para platos con un maximo de 42 dientes - Jaula larga de Aluminio",
    }, {
        id: 41,
        titulo: "Batería para grupo Sram Etap/AXS",
        imagen: "./imagenes/grupos/sram/sram-imagen18.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 38021,
        cantidad: 10,
        description: "Batería para grupos electrónicos Sram Red Etap/AXS.",
    }, {
        id: 42,
        titulo: "Shifter de bicicleta de montaña Sram SX Eagle Trigger 1x12",
        imagen: "./imagenes/grupos/sram/sram-imagen19.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 20337,
        cantidad: 10,
        description: "El mando de cambio SRAM SX Eagle Trigger de 12 velocidades es compatible con todas las otras transmisiones SRAM Eagle. También disponible como opción de cambio Eagle específico para E-MTB.",
    }, {
        id: 43,
        titulo: "Cambio Trasero SRAM Roldanas de Cambio Force 22 /Rrival 22 11v",
        imagen: "./imagenes/grupos/sram/sram-imagen20.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 10316,
        cantidad: 10,
        description: "El conjunto de roldanas SRAM es adecuado para los descarriladores trasero SRAM Force 22 y Rrival 22 (11x2).",
    }, {
        id: 44,
        titulo: "Cambio Trasero SRAM Roldanas de Cambio Force/Rrival/Apex",
        imagen: "./imagenes/grupos/sram/sram-imagen21.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 9432,
        cantidad: 10,
        description: "El conjunto de roldanas de cerámica SRAM es adecuado para los descarrilador trasero SRAM Force/Rrival/Apex.",
    }, {
        id: 45,
        titulo: "Piñon SRAM 12v MTB PG-1230 11-50d HG Black (NX Eagle)",
        imagen: "./imagenes/grupos/sram/sram-imagen23.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 55705,
        cantidad: 10,
        description: "Piñon para bicicletas de montaña de 12 velocidades Sram NX Eagle (XG1230), con dentado de 11-50 y compatible con núcleos estriados de 9/10/11v.",
    }, {
        id: 46,
        titulo: "Cadena Bicicleta de 12 velocidades Sram PC XX1 Eagle",
        imagen: "./imagenes/grupos/sram/sram-imagen22.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 49810,
        cantidad: 10,
        
        description: "Cadena de bicicleta de montaña de 12 velocidades Sram PC XX1 Eagle.",
    }, {
        id: 47,
        titulo: "Cadena Bicicleta de 12 velocidades Sram PC X01 Eagle",
        imagen: "./imagenes/grupos/sram/sram-imagen24.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 35074,
        cantidad: 10,
        description: "Cadena de bicicleta de montaña de 12 velocidades Sram PC X01 Eagle.",
    }, {
        id: 47,
        titulo: "Cadena de Bicicleta de 12 velocidades Sram Red AXS",
        imagen: "./imagenes/grupos/sram/sram-imagen25.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 38316,
        cantidad: 10,
        description: "Cadena de Bicicleta de ruta de 12 velocidades Sram Red Etap.",
    }, {
        id: 48,
        titulo: "Cadena de Bicicleta de 11 velocidades Sram PC RED 22",
        imagen: "./imagenes/grupos/sram/sram-imagen26.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 23284,
        cantidad: 10,
        description: "Cadena de 11 velocidades Sram PC RED 22.",
    }, {
        id: 49,
        titulo: "Conector de Cadena Sram Powerlink",
        imagen: "./imagenes/grupos/sram/sram-imagen27.jpg",
        categoria: {
            id: "componentes",
        },
        marca: "sram",
        precio: 1400,
        cantidad: 10,
        description: "Conector de cadena SRAM.",
    }, {
        id: 50,
        titulo: "Casco Giro Aether Spherical",
        imagen: "./imagenes/cascos/1.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "giro",
        precio: 127610,
        cantidad: 2,
        talle: "unico",
        description: "Desde la elegante silueta de su diseño industrial hasta la forma en que este casco gestiona la energía del impacto, el aether spherical no se parece a ningún otro casco jamás creado y es un verdadero testimonio de la innovación en el rendimiento.",
    }, {
        id: 51,
        titulo: "Casco Giro Manifest Spherical",
        imagen: "./imagenes/cascos/2.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "giro",
        precio: 106579,
        cantidad: 3,
        talle: "L",
        description: "Con tecnología esférica, la mejor ventilación de su clase, cobertura profunda y comodidad de lujo, manifest es el casco de montaña más premium disponible.",
    }, {
        id: 52,
        titulo: "Casco Giro Helios Spherical",
        imagen: "./imagenes/cascos/3.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "giro",
        precio: 107716,
        cantidad: 4,
        talle: "M",
        description: "El CASCO GIRO HELIOS SPHERICAL MIPS es perfecto para quienes practican el ciclismo de ruta.",
    }, {
        id: 53,
        titulo: "Casco Bell Star Pro",
        imagen: "./imagenes/cascos/4.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "bell",
        precio: 94642,
        cantidad: 1,
        talle: "unico",
        description: "No es un modelo muy convencional, sino que se trata de un casco con perfil aerodinámico, con varios detalles que normalmente la gran mayoría no traen.",
    }, {
        id: 54,
        titulo: "Casco Giro Synthe Mips II",
        imagen: "./imagenes/cascos/5.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "giro",
        precio: 90663,
        cantidad: 3,
        talle: "54-58",
        description: "El Synthe MIPS II es un ícono, actualizado para ser más fresco y cómodo que nunca.",
    }, {
        id: 55,
        titulo: "Casco de ciclismo Lazer modelo Century",
        imagen: "./imagenes/cascos/6.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "lazer",
        precio: 71695,
        cantidad: 3,
        talle: "L",
        description: "El casco Century es el resultado de 100 años de experiencia. Mediante la integración de todo el conocimiento y las necesidades de los usuarios en un concepto, el Century ofrece una nueva referencia que no requiere prioridades en cuanto a protección.",
    }, {
        id: 56,
        titulo: "Casco Ciclismo Bell XR Spherical Mips",
        imagen: "./imagenes/cascos/7.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "bell",
        precio: 83158,
        cantidad: 2,
        talle: "unico",
        description: "El XR Spherical es un casco versátil que puede utilizarse para ruta, para montaña o ser parte de tu viaje del mundo. Es el casco que abre las posibilidades para una exploración sin fin.",
    }, {
        id: 57,
        titulo: "Casco Ciclismo Giro Cinder Mips",
        imagen: "./imagenes/cascos/8.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "giro",
        precio: 67926,
        cantidad: 2,
        talle: "unico",
        description: "El casco Giro Cinder MIPS llega con una estética similar al popular modelo Synthe pero incorpora el sistema de ajuste Roc Loc 5 que permite un mejor ajuste del casco a la cabeza, el interior Air-FX que mejora el confort y el sistema de seguridad MIPS.",
    }, {
        id: 58,
        titulo: "Casco Ciclismo Giro Ember Mips",
        imagen: "./imagenes/cascos/9.jpg",
        categoria: {
            id: "cascos",
        },
        marca: "giro",
        precio: 67926,
        cantidad: 1,
        talle: "s",
        
        description: "El casco Giro Ember MIPS para mujer llega con una estética similar al popular modelo Synthe pero incorpora el sistema de ajuste RocLoc 5 que permite un mejor ajuste del casco a la cabeza.",
    }, {
        id: 59,
        titulo: "Grupo Electronico Ruta Sram Red eTap AXS 2X D1 HRD FM Freno Hidraulico 2x12",
        imagen: "./imagenes/grupos/sram/electronico1.jpg",
        categoria: {
            id: "grupos",
        },
        marca: "sram",
        precio: 1440360,
        description: "El set de grupo de cambios de 6 agujeros de SRAM Red eTap AXS™ HRD FM para 2x12 disco te ofrece un equipo con funciones intuitivas orientadas al rendimiento.",
}, {
        id: 60,
        titulo: "Grupo Electronico Ruta Sram Force eTap AXS , Frenos hidraulicos 2x12",
        imagen: "./imagenes/grupos/sram/electronico2.jpg",
        categoria: {
            id: "grupos",
        },
        marca: "sram",
        precio: 888618,
        description: "Grupo de bicicleta de ruta Electrónico Inalambrico 2x12 Sram Force AXS, con frenos de disco hidraulicos, para núcleos XDR.",
    }, {
        id: 61,
        titulo: "Grupo MTB Sram GX Eagle DUB Boost 175mm 32T 1x12 Lunar",
        imagen: "./imagenes/grupos/sram/gxEgle.jpg",
        categoria: {
            id: "grupos",
        },
        marca: "sram",
        precio: 264968,
        description: "GX Eagle combina la capacidad completa de las tecnologías Eagle, en un grupo que se da cuenta del potencial dentro de cada construcción. Aquí es donde encontrarás las mejores bielas de aluminio para MTB.",
       
    },
]